(function registerVaRRIExamples(root) {
  'use strict';

  const featureOverviewProfile = [
    '# unpaired probabilities',
    '1 0.9',
    '2 0.7',
    '3 0.3',
    '4 0.1',
    '7 0.3',
    '8 0.7',
    '9 0.6',
  ].join('\n');

  const coronelTellezProfile1 = [
    '61 0.6',
    '62 1',
    '63 0.6',
    '64 0.2',
    '65 0.2',
    '66 1',
    '67 0.2',
    '68 0.2',
    '69 0.2',
    '70 0.2',
    '71 0.6',
    '72 1',
    '73 0.6',
    '74 0.6',
    '75 1',
    '76 1',
    '77 0.2',
    '78 0.2',
    '79 0.2',
    '80 0.6',
    '81 0.6',
    '82 0.2',
    '83 0.6',
    '84 0.2',
    '85 0.6',
    '86 0.6',
    '87 0.6',
    '88 0.2',
    '89 0.2',
    '90 0.2',
    '91 0.2',
    '92 0.2',
    '93 0.2',
    '94 0.6',
    '95 0.6',
    '96 0.2',
    '97 0',
    '98 1',
    '99 0.6',
    '100 0.2',
    '101 1',
    '102 0.6',
    '103 0.2',
    '104 0.2',
    '105 0',
    '106 0.2',
    '107 0.2',
  ].join('\n');

  const coronelTellezProfile2 = [
    '64 0.6',
    '65 0.2',
    '66 0.2',
    '67 0',
    '68 0.6',
    '69 0.6',
    '70 0.2',
    '71 0.2',
    '72 0',
    '73 1',
    '74 0.2',
    '75 0.2',
    '76 0',
    '77 0.6',
    '78 0.2',
    '79 0.2',
    '80 0.2',
    '81 0.2',
    '82 0.2',
    '83 0.2',
    '84 0.2',
    '85 0.2',
    '86 0.2',
    '87 0.2',
    '88 0.6',
    '89 0.2',
    '90 1',
    '91 0.6',
    '92 0.6',
    '93 1',
    '94 0.2',
    '95 0.2',
    '96 1',
    '97 0.2',
    '98 0.2',
    '99 0.2',
    '100 0.6',
    '101 0.2',
    '102 0.2',
    '103 0.2',
    '104 0',
    '105 0',
    '106 0',
    '107 0.6',
  ].join('\n');

  const examples = {
    '2mol': {
      name: 'RNA–RNA interaction feature overview',
      nameShort: 'All feature showcase',
      description: 'Demonstrates cropping, probability profiles, region and subsequence highlights, and point mutations in one interaction.',
      descriptionShort: 'Showcases all features of vaRRI-js.',
      vaRRIParams: {
        sequence: 'ACGAUCCCAUGGAUUAGAGCAUUUUCGACAGCAG&ACGAAAAAAAGAGCAGACAGUAG',
        structure: '..<<..<<...>>>>...((....(((...((..&............)))))..))..',
        startIndex1: -6,
        startIndex2: 100,
        coloring: 'strand',
        highlighting: 'region',
        backgroundhighlighting: 'basepairs',
        forceLayoutLinearRRI: 1,
        distinctBpTypes: 1,
        cropping: 2,
        forceLayout: 0,
        regionHighlights: '21-25&113-114:0d00ff:0.2',
        subseqHighlights: '1:15-18:338a29:1,2:117-118:1e1ee4:0.7',
        mutations: '1:20G:338a29,2:115C:1e1ee4',
        profileData1: featureOverviewProfile,
        profileIdxRef1: 1,
        profileColorRepresentsOne1: 1,
        profileColorRepresentsOne2: 0,
      },
    },
    'coronel-tellez-2022': {
      name: 'sRNA-controlled iron sparing response in Staphylococci',
      nameShort: 'SHAPE annotation & cropping',
      authors: 'Coronel-Tellez, et al., 2022',
      doi: 'http://dx.doi.org/10.1093/nar/gkac648',
      description: 'Reproduction of *Figure 6A-bottom* [(Coronel-Tellez, et al., 2022)](http://dx.doi.org/10.1093/nar/gkac648) showing an interaction with position-specific SHAPE probing data annotation and subsequence highlighting. The long input sequences are cropped to the region of interaction +3 nucleotides.',
      descriptionShort: 'Position-specific SHAPE probing data annotation and cropping of long sequences to RRI region.',
      vaRRIParams: {
        sequence: 'AAUUCUAUCUGAAAGAUGUGUGGGGCAUCGUUAUUUUAGGUGGAUAUGAGCAAUUUAUUAAAAGUCAUUUACGGAAAAUAUAUAUAGACGGGGUGAGUAAUAUGCAAGAACAUUUGGUGGUUACACUUGAUAGCAAAGGAGAAGAACUU&UUGAAAAUGAUUAUCAAUACCACAUAGAACAUCCCCCCCACAACGUUUCGUUCUUGUUGGAUUGGUCAUUUUCAAAUAUUCCCCUUUUAUAUGCCCGUAAAAGACAAUAUACGUUAUAACAACGUUUUAUAAAAGCAGUAAACCCUUACGACACUUUAGGUUUACUGCUUUUGU',
        structure: '...............................................................(((.(((((((......((((((((.((((.((((((.(((.............................................&..................................................................))))......))))))))))))))))).))))))).))).....................................................................',
        colorSeq1: 'c9c1c9',
        colorSeq2: 'c9c1c9',
        startIndex1: 1,
        startIndex2: 1,
        cropping: 3,
        forceLayout: 'off',
        backgroundhighlighting: 'nothing',
        highlighting: 'basepairs',
        subseqHighlights: '1:88-93:0f50b8:1,1:102-104:0e7a06:1,2:81-84:e012dd:1,2:94-96:e012dd:1',
        profileData1: coronelTellezProfile1,
        profileColorRepresentsOne1: 1,
        profileColor1: 'ea373c',
        profileData2: coronelTellezProfile2,
        profileColorRepresentsOne2: 1,
        profileColor2: 'ea373c',
      },
    },
    'wu-2024': {
      name: 'RNA interactome of hypervirulent Klebsiella pneumoniae reveals a small RNA inhibitor of capsular mucoviscosity and virulence',
      nameShort: 'Mutations & highlighting',
      authors: 'Wu et al., 2024',
      doi: 'https://doi.org/10.1101/2024.06.23.600155',
      description: 'Reproduction of Figure 4C [(Wu et al., 2024)](https://doi.org/10.1101/2024.06.23.600155) showing an interaction with 4 mutations and a subsequence highlighting within a sequence context upstream of the start codon.',
      descriptionShort: 'Subsequence highlighting and mutations within a sequence context.',
      vaRRIParams: {
        sequence: 'AACUCGCGAAAGCCAUAAAAACCAGGGAGACA&UUCCCUGGUGUUGGCGCAGUAUUCGCGCA',
        structure: '....((((((.((((.....((((((((....&.))))))))..))))......))))))..',
        startIndex1: -35,
        startIndex2: 2,
        subseqHighlights: '1:-12--6:0dec3f:0.9',
        mutations: '1:-14G:fb0bcb,1:-13G:fb0bcb,2:8C:fb0bcb,2:9C:fb0bcb',
        forceLayout: 'off',
      },
    },    
    'IntaRNA-seeds': {
      name: 'Showcasing potential seed regions considered by IntaRNA',
      nameShort: 'IntaRNA seed regions',
      description: 'Highlighting of the two potential seed interactions considered by IntaRNA to predict the shown interaction between the two sequences. The highlighting is done using a semi-transparent purple color, which allows to show overlapping regions.',
      descriptionShort: 'Opaque highlighting of multiple potential IntaRNA seed regions.',
      vaRRIParams: {
        sequence:'CUUAGCCGUAAUUGGAUUAGCUGAUGAACAAACUUCUCGUGAGUCUGCUGUUGACCCUGGGUCUGAC&GAGAGACCCACGCAGUCGGACUCUUCAGAUUAUCUCCUCAUCAGGCUAAUCACGGUUUUU',
        colorSeq1:'#add8e6',
        startIndex1:-23,
        colorSeq2:'#f4bb44',
        startIndex2:64,
        structure:'...((((((.....(((((((((((((.......(((...((((((((((.......(((((((...&...)))))))..))).)))))))...)))........)))))).)))))))))))))...',
        colorBasepair:'#ff0000',
        coloring:'strand',
        highlighting:'region',
        colorRriNodes:'#ff0000',
        forceLayoutLinearRRI: 1,
        distinctBpTypes:1,
        regionHighlights:'35-41&67-73:0D00FF:0.4,-9--3&108-114:0D00FF:0.4',
        forceLayout: 'off',
      },
    },
    'crossing-rri': {
      name: 'Crossing RRI showcase',
      nameShort: 'Crossing RRI via force field',
      descriptionShort: 'Crossing RNA–RNA interaction resolved via relaxed force-field layout.',
      description: 'Crossing RNA–RNA interactions (w.r.t. the underlying joint-structure layout algorithm of fornac) are typically problematic since their base pairing forms a crossing pseudoknot structure. Some can be layouted when relaxing the force field (see Visualization Settings).',
      vaRRIParams: {
        sequence: 'nnnnnnnnnnnnnnnnn&nnnnnnnnnnnnn',
        structure:'((..((...<<<..<<<&))))...>>>>>>',
        distinctBpTypes: 0,
        forceLayout: 1,
        forceLayoutFreeTails: 1,
        forceLayoutPullCrossing: 1,
      },  
    },    
  };

  root.VARRI_EXAMPLES = examples;

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = examples;
  }
})(typeof window !== 'undefined' ? window : globalThis);
